#!/usr/bin/env python3
"""Parse LTspice .log files from the corner-sweep test benches.

Consumes the .log file produced by running one of the test benches
generated by tools/gen_freq_testbench.py or
tools/gen_sensitivity_testbench.py in LTspice, and emits paper-ready
CSV / LaTeX / macros under paper/data/.

The .log format used by LTspice for `.meas` results varies a bit by
version. Two forms are accepted:

  Inline form (older LTspice):
      .step freq=10000
      v_oh: MAX(v(out)) FROM 0 TO 2e-4 = -0.8
      v_ol: MIN(v(out)) FROM 0 TO 2e-4 = -3.6

  Summary-table form (newer LTspice):
      Measurement: v_oh
         step  MAX(v(out))    FROM       TO
            1  -8.000000e-01  5.50e-05   1.00e-04
            2  -1.200000e+00  5.50e-06   1.00e-05

The parser tries both and merges per step index.

Usage:
    python tools/analyze_ltspice_log.py --sweep freq
    python tools/analyze_ltspice_log.py --sweep sensitivity
    python tools/analyze_ltspice_log.py --log path/to/file.log
"""

import argparse
import csv
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SWEEPS_DIR = PROJECT_ROOT / "analysis" / "sweeps"
PAPER_DATA = PROJECT_ROOT / "paper" / "data"

V_HIGH_SPEC = -0.8
V_LOW_SPEC = -3.6
V_THRESHOLD = (V_HIGH_SPEC + V_LOW_SPEC) / 2.0

# Logic margin threshold for declaring f_max: swing must remain above this
# fraction of the nominal swing. 0.8 is a defensible conservative criterion.
SWING_KEEP_FRAC = 0.8


# ---------------------------------------------------------------- parsing

RE_STEP = re.compile(
    r"\.step\s+(?:\w+=\S+\s*)*([a-zA-Z_]\w*)\s*=\s*([-+\d.eE]+)"
)
# Inline form: "name: ... = value" -- LTspice often has multiple "=" signs
# in TRIG(...) / TARG(...) clauses, so we look for the LAST "= <number>"
# in the line (the .meas result), not the first.
RE_INLINE_NAME = re.compile(r"^\s*([a-zA-Z_]\w*)\s*:")
RE_LAST_VALUE = re.compile(r"=\s*([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)\s*(?:FROM\b.*)?$")
# Summary table header: "Measurement: name"
RE_MEAS_HEADER = re.compile(r"^\s*Measurement:\s*([a-zA-Z_]\w*)\s*$")
# Summary table row: " 1   -8.0e-01  5.5e-05  1e-04"
RE_TABLE_ROW = re.compile(r"^\s*(\d+)\s+([-+\d.eE]+)")


def parse_log(text: str) -> tuple:
    """Return (steps, measurements).

    steps: list of dicts, one per .step, with the param name -> value mapping.
           e.g. [{"freq": 10000}, {"freq": 20000}, ...]
    measurements: dict of measurement name -> list of floats indexed by step.
           e.g. {"v_oh": [-0.8, -1.2, ...], "v_ol": [-3.6, -3.5, ...]}
    """
    steps = []
    measurements = {}
    current_step_idx = None  # 1-based; matches LTspice numbering
    in_measurement = None    # for the summary-table form

    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]

        m = RE_STEP.search(line)
        if m:
            name, value = m.group(1), float(m.group(2))
            steps.append({name: value})
            current_step_idx = len(steps)
            in_measurement = None
            i += 1
            continue

        m = RE_MEAS_HEADER.match(line)
        if m:
            in_measurement = m.group(1)
            measurements.setdefault(in_measurement, [])
            i += 1
            # Skip header row of the table
            if i < len(lines):
                i += 1
            continue

        if in_measurement is not None:
            m = RE_TABLE_ROW.match(line)
            if m:
                step_idx = int(m.group(1))
                val = float(m.group(2))
                lst = measurements[in_measurement]
                # Grow to required size with None padding.
                while len(lst) < step_idx:
                    lst.append(None)
                lst[step_idx - 1] = val
                i += 1
                continue
            # Blank line or new section ends the table.
            if line.strip() == "" or RE_MEAS_HEADER.match(line):
                in_measurement = None
                # don't advance i, let the loop reconsider
                if line.strip() == "":
                    i += 1
                continue

        # Inline form: "name: ... = value" (use the RIGHTMOST "= number"
        # so TRIG(...) / TARG(...) clauses inside the line don't fool us).
        m_name = RE_INLINE_NAME.match(line)
        if m_name and current_step_idx is not None:
            # Scan for the last "= <number>" in the line.
            matches = list(RE_LAST_VALUE.finditer(line))
            if matches:
                name = m_name.group(1)
                value = float(matches[-1].group(1))
                lst = measurements.setdefault(name, [])
                while len(lst) < current_step_idx:
                    lst.append(None)
                lst[current_step_idx - 1] = value
                i += 1
                continue

        i += 1

    return steps, measurements


# ---------------------------------------------------------------- assemble rows

def rows_from(steps, measurements):
    """Combine step parameters and measurements into a list of dicts."""
    rows = []
    for idx, step in enumerate(steps):
        row = dict(step)
        for meas_name, values in measurements.items():
            row[meas_name] = values[idx] if idx < len(values) else None
        rows.append(row)
    return rows


# ---------------------------------------------------------------- writers

def write_csv(rows, path: Path, columns: list = None):
    path.parent.mkdir(parents=True, exist_ok=True)
    if columns is None:
        columns = sorted({k for r in rows for k in r})
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(columns)
        for r in rows:
            w.writerow([r.get(c) for c in columns])


def fmt(x, places=3):
    if x is None:
        return "--"
    try:
        return f"{float(x):.{places}f}"
    except (ValueError, TypeError):
        return str(x)


# ---------------------------------------------------------------- freq sweep

def analyse_freq(log_path: Path):
    text = log_path.read_text(encoding="utf-8", errors="ignore")
    steps, meas = parse_log(text)
    rows = rows_from(steps, meas)
    if not rows:
        sys.exit(f"ERROR: parsed no rows from {log_path}")

    # Sort by freq for sensible plotting / reading.
    rows.sort(key=lambda r: r.get("freq") or 0)

    # Nominal swing comes from the lowest-frequency step (where the
    # gate has plenty of time to settle).
    nominal_swing = rows[0].get("swing")
    if nominal_swing is None and rows[0].get("v_oh") is not None and rows[0].get("v_ol") is not None:
        nominal_swing = rows[0]["v_oh"] - rows[0]["v_ol"]

    # f_max: highest freq where swing >= SWING_KEEP_FRAC * nominal.
    fmax_hz = None
    if nominal_swing:
        threshold = SWING_KEEP_FRAC * nominal_swing
        for r in rows:
            s = r.get("swing")
            if s is None and r.get("v_oh") is not None and r.get("v_ol") is not None:
                s = r["v_oh"] - r["v_ol"]
            if s is not None and s >= threshold:
                fmax_hz = r.get("freq")

    # Output paths
    csv_path = PAPER_DATA / "freq_sweep.csv"
    tex_path = PAPER_DATA / "freq_sweep.tex"
    mac_path = PAPER_DATA / "freq_sweep_macros.tex"

    write_csv(rows, csv_path,
              columns=["freq", "v_oh", "v_ol", "swing",
                       "t_pd_rise", "t_pd_fall"])

    # LaTeX summary table: every decade rather than every step (cleaner).
    decade_rows = []
    seen_decades = set()
    for r in rows:
        if r.get("freq") is None:
            continue
        decade = int(round(__import__("math").log10(r["freq"])))
        if decade not in seen_decades:
            decade_rows.append(r)
            seen_decades.add(decade)
        elif r["freq"] / (10 ** decade) > (decade_rows[-1]["freq"] / (10 ** decade) if decade_rows else 0):
            # keep the highest-in-decade representative point
            pass

    tex_lines = [
        "% Auto-generated by tools/analyze_ltspice_log.py --sweep freq",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Maximum clock frequency of a SiC JFET RTL inverter chain"
        r" from an LTspice transient sweep. The test bench is a"
        r" \texttt{tools/gen\_freq\_testbench.py}-generated 4-inverter chain"
        r" (equivalent depth to the ALU 4-bit ripple-carry critical path),"
        r" with input/output measured at the logic threshold $V_{th}=-2.2$\,V."
        r" $f_{\max}$ is the highest swept frequency at which the output swing"
        r" remains $\geq$" + f"{int(SWING_KEEP_FRAC*100)}" + r"\% of the"
        r" low-frequency reference. Configuration and resistor values are"
        r" taken from \texttt{cpus/4004/config.py}.}",
        r"\label{tab:freq-sweep}",
        r"\begin{tabular}{@{}rrrrr@{}}",
        r"\toprule",
        r"Frequency (kHz) & $V_{OH}$ (V) & $V_{OL}$ (V) &"
        r" Swing (V) & $t_{pd}$ rise ($\mu$s) \\",
        r"\midrule",
    ]
    for r in rows:
        if r.get("freq") is None:
            continue
        tex_lines.append(
            rf"{r['freq']/1e3:.1f} & "
            rf"{fmt(r.get('v_oh'), 3)} & "
            rf"{fmt(r.get('v_ol'), 3)} & "
            rf"{fmt(r.get('swing') if r.get('swing') is not None else (r.get('v_oh',0)-r.get('v_ol',0) if r.get('v_oh') is not None and r.get('v_ol') is not None else None), 3)} & "
            rf"{fmt(r['t_pd_rise']*1e6, 3) if r.get('t_pd_rise') else '--'} \\"
        )
    tex_lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    tex_path.write_text("\n".join(tex_lines) + "\n", encoding="utf-8")

    mac_lines = [
        "% Auto-generated by tools/analyze_ltspice_log.py --sweep freq",
        rf"\newcommand{{\FmaxKHz}}{{{fmax_hz/1e3:.0f}}}" if fmax_hz else
        rf"\newcommand{{\FmaxKHz}}{{?}}",
        rf"\newcommand{{\NominalSwingV}}{{{nominal_swing:.2f}}}" if nominal_swing else
        rf"\newcommand{{\NominalSwingV}}{{?}}",
    ]
    mac_path.write_text("\n".join(mac_lines) + "\n", encoding="utf-8")

    print(f"# Parsed {len(rows)} freq steps from {log_path.name}")
    if fmax_hz:
        print(f"#   f_max ({int(SWING_KEEP_FRAC*100)}% swing retained) = {fmax_hz/1e3:.0f} kHz")
        print(f"#   nominal swing at lowest freq = {nominal_swing:.2f} V")
    print(f"# Wrote {csv_path}")
    print(f"# Wrote {tex_path}")
    print(f"# Wrote {mac_path}")


# ---------------------------------------------------------------- sensitivity sweep

AXIS_LABEL = {
    "r1": ("$R_1$", "k$\\Omega$", 1e-3),
    "r2": ("$R_2$", "k$\\Omega$", 1e-3),
    "r3": ("$R_3$", "k$\\Omega$", 1e-3),
    "vpos": ("$V_{POS}$", "V", 1.0),
    "vneg": ("$V_{NEG}$", "V", 1.0),
}


def analyse_sensitivity(sweeps_dir: Path):
    """Walk every sensitivity_<axis>.log under analysis/sweeps/."""
    per_axis = {}
    for axis in AXIS_LABEL:
        log_path = sweeps_dir / f"sensitivity_{axis}.log"
        if not log_path.is_file():
            continue
        text = log_path.read_text(encoding="utf-8", errors="ignore")
        steps, meas = parse_log(text)
        rows = rows_from(steps, meas)
        if rows:
            per_axis[axis] = rows
        else:
            print(f"!! parsed no rows from {log_path}", file=sys.stderr)

    if not per_axis:
        sys.exit(f"ERROR: no sensitivity_*.log files in {sweeps_dir}")

    # CSV: one row per (axis, step).
    flat = []
    for axis, rows in per_axis.items():
        for r in rows:
            r2 = dict(r)
            r2["axis"] = axis
            flat.append(r2)
    csv_path = PAPER_DATA / "sensitivity.csv"
    write_csv(flat, csv_path,
              columns=["axis", "r1", "r2", "r3", "vpos", "vneg",
                       "v_oh", "v_ol", "swing", "t_pd_rise", "t_pd_fall"])

    # Compute worst-case noise margins per axis.
    worst = {}
    for axis, rows in per_axis.items():
        nm_h_min = float("inf")
        nm_l_min = float("inf")
        for r in rows:
            if r.get("v_oh") is not None:
                nm_h_min = min(nm_h_min, r["v_oh"] - V_THRESHOLD)
            if r.get("v_ol") is not None:
                nm_l_min = min(nm_l_min, V_THRESHOLD - r["v_ol"])
        worst[axis] = (nm_h_min, nm_l_min)

    overall_min = min(min(h, l) for (h, l) in worst.values()
                      if h != float("inf") and l != float("inf"))

    # LaTeX table: one row per axis.
    tex_lines = [
        "% Auto-generated by tools/analyze_ltspice_log.py --sweep sensitivity",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Sensitivity of the SiC JFET RTL inverter's noise margins"
        r" to single-axis variation of each hand-tuned parameter, from"
        r" LTspice transient sweeps. Each row is an independent sweep of"
        r" one parameter over $\pm 20\%$ of nominal (resistors) or $\pm 2$\,V"
        r" (supplies), with the other parameters fixed at"
        r" \texttt{cpus/4004/config.py} values. $NM_H = V_{OH} - V_{th}$"
        r" and $NM_L = V_{th} - V_{OL}$, with $V_{th}=-2.2$\,V.}",
        r"\label{tab:sensitivity}",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"Swept parameter & Range & $NM_H^{\min}$ (V) & $NM_L^{\min}$ (V) \\",
        r"\midrule",
    ]
    for axis, (h, l) in worst.items():
        label, unit, scale = AXIS_LABEL[axis]
        rows = per_axis[axis]
        vals = [r.get(axis) for r in rows if r.get(axis) is not None]
        rng = f"{min(vals)*scale:g} -- {max(vals)*scale:g}\\,{unit}" if vals else "--"
        tex_lines.append(
            rf"{label} & {rng} & {fmt(h, 2)} & {fmt(l, 2)} \\"
        )
    tex_lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    tex_path = PAPER_DATA / "sensitivity.tex"
    tex_path.write_text("\n".join(tex_lines) + "\n", encoding="utf-8")

    mac_path = PAPER_DATA / "sensitivity_macros.tex"
    mac_path.write_text(
        "% Auto-generated by tools/analyze_ltspice_log.py --sweep sensitivity\n"
        rf"\newcommand{{\WorstNoiseMargin}}{{{overall_min:.2f}}}" + "\n"
        rf"\newcommand{{\LogicThresholdV}}{{{V_THRESHOLD:.1f}}}" + "\n",
        encoding="utf-8",
    )

    print(f"# Parsed {sum(len(r) for r in per_axis.values())} sensitivity rows"
          f" across {len(per_axis)} axes")
    for axis, (h, l) in worst.items():
        print(f"#   {axis}: NM_H_min={h:+.3f} V  NM_L_min={l:+.3f} V")
    print(f"#   overall worst noise margin = {overall_min:+.3f} V")
    print(f"# Wrote {csv_path}")
    print(f"# Wrote {tex_path}")
    print(f"# Wrote {mac_path}")


# ---------------------------------------------------------------- main

def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--sweep", choices=("freq", "sensitivity"),
                   help="which sweep to analyse")
    p.add_argument("--log", default=None,
                   help="explicit log path (default: analysis/sweeps/<sweep>_testbench.log"
                        " or sensitivity_*.log)")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    if args.log:
        # Single-file mode.
        log_path = Path(args.log)
        if not log_path.is_file():
            sys.exit(f"ERROR: {log_path} not found")
        if args.sweep == "freq" or "freq" in log_path.stem:
            analyse_freq(log_path)
        else:
            analyse_sensitivity(log_path.parent)
        return

    if args.sweep == "freq":
        log_path = SWEEPS_DIR / "freq_testbench.log"
        if not log_path.is_file():
            sys.exit(f"ERROR: {log_path} not found. Run LTspice on "
                     f"analysis/sweeps/freq_testbench.cir first.")
        analyse_freq(log_path)
    elif args.sweep == "sensitivity":
        if not SWEEPS_DIR.is_dir() or not list(SWEEPS_DIR.glob("sensitivity_*.log")):
            sys.exit(f"ERROR: no sensitivity_*.log files in {SWEEPS_DIR}. Run "
                     f"LTspice on analysis/sweeps/sensitivity_*.cir first.")
        analyse_sensitivity(SWEEPS_DIR)
    else:
        p.error("--sweep required when no --log given")


if __name__ == "__main__":
    main()
