#!/usr/bin/env python3
"""Count JFET and resistor instances per CPU subsystem.

Walks the LTspice .asc schematics referenced from a CPU project's
config.py COMPONENTS list and counts SYMBOL instances. Emits a CSV and a
LaTeX booktabs table for the paper.

Output is regenerated every time the script runs, so the paper stays in
sync with whatever the user has on disk -- if the CPU is edited, just
re-run and the numbers update.

Usage:
    python tools/count_transistors.py                   # cpu=4004, full
    python tools/count_transistors.py --cpu 4004
    python tools/count_transistors.py --csv out.csv --tex out.tex
    python tools/count_transistors.py --quiet           # no stdout summary
"""

import argparse
import csv
import importlib.util
import os
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CPUS_DIR = PROJECT_ROOT / "cpus"
PAPER_DATA_DIR = PROJECT_ROOT / "paper" / "data"

SYMBOL_NJF = re.compile(r"^SYMBOL njf\b", re.MULTILINE)
SYMBOL_RES = re.compile(r"^SYMBOL res\b", re.MULTILINE)

PRETTY = {
    "ALU":     "Arithmetic logic unit",
    "IR":      "Instruction register",
    "MI":      "Micro-instruction decoder",
    "Cont":    "Control logic",
    "Pin":     "External pins and bus",
    "PC":      "Program counter",
    "Counter": "Step counter",
    "Scratch": r"Scratch pad ($16\times 4$-bit)",
    "Stack":   "Subroutine stack (3-level)",
}


def load_config(cpu_name: str):
    """Import cpus/<cpu>/config.py and return (module, cpu_dir)."""
    cpu_dir = CPUS_DIR / cpu_name
    cfg_path = cpu_dir / "config.py"
    if not cfg_path.is_file():
        sys.exit(f"ERROR: {cfg_path} not found")
    spec = importlib.util.spec_from_file_location(f"_cpu_{cpu_name}_config", cfg_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod, cpu_dir


def count_in_file(path: Path):
    """Return (njf_count, res_count) for one .asc file."""
    if not path.is_file():
        print(f"WARN: missing schematic {path}", file=sys.stderr)
        return (0, 0)
    text = path.read_text(encoding="utf-8", errors="ignore")
    return (len(SYMBOL_NJF.findall(text)), len(SYMBOL_RES.findall(text)))


def parts_for_composable(spec: dict):
    """Files needed for a composable component at full capacity.

    Always returns common + every group file + every individual part.
    This gives the worst-case (largest) CPU configuration, which is
    what we want to quote in the paper.
    """
    parts = list(spec.get("common", []))
    parts.extend(spec.get("groups", {}).keys())
    parts.extend(spec["parts"].values())
    return parts


def collect(cpu_name: str):
    cfg, cpu_dir = load_config(cpu_name)
    rows = []
    for prefix, spec in cfg.COMPONENTS:
        subsystem = prefix.rstrip("_")
        if isinstance(spec, str):
            njf, res = count_in_file(cpu_dir / spec)
            files = [spec]
        elif isinstance(spec, dict):
            folder = cpu_dir / spec["folder"]
            files = parts_for_composable(spec)
            njf = res = 0
            for fname in files:
                n, r = count_in_file(folder / fname)
                njf += n
                res += r
            files = [f"{spec['folder']}/{f}" for f in files]
        else:
            continue
        rows.append({
            "subsystem": subsystem,
            "pretty":    PRETTY.get(subsystem, subsystem),
            "files":     files,
            "file_count": len(files),
            "njf":       njf,
            "res":       res,
        })
    return rows


def write_csv(rows, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["subsystem", "pretty_name", "file_count", "njf", "resistors", "files"])
        for r in rows:
            w.writerow([r["subsystem"], r["pretty"], r["file_count"],
                        r["njf"], r["res"], ";".join(r["files"])])
        w.writerow(["TOTAL", "Total", sum(r["file_count"] for r in rows),
                    sum(r["njf"] for r in rows), sum(r["res"] for r in rows), ""])


def write_macros(rows, path: Path):
    """Emit \\newcommand macros so prose can reference live numbers."""
    path.parent.mkdir(parents=True, exist_ok=True)
    total_njf = sum(r["njf"] for r in rows)
    total_res = sum(r["res"] for r in rows)
    by_sub = {r["subsystem"]: r for r in rows}
    out = []
    out.append("% Auto-generated by tools/count_transistors.py -- do not edit by hand.")
    out.append(rf"\newcommand{{\TotalJFETCount}}{{{total_njf}}}")
    out.append(rf"\newcommand{{\TotalResistorCount}}{{{total_res}}}")
    for sub, row in by_sub.items():
        out.append(rf"\newcommand{{\JFETCount{sub}}}{{{row['njf']}}}")
        out.append(rf"\newcommand{{\ResistorCount{sub}}}{{{row['res']}}}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def write_tex(rows, path: Path, caption=None, label=None):
    path.parent.mkdir(parents=True, exist_ok=True)
    total_njf = sum(r["njf"] for r in rows)
    total_res = sum(r["res"] for r in rows)
    out = []
    out.append("% Auto-generated by tools/count_transistors.py -- do not edit by hand.")
    out.append(r"\begin{table}[t]")
    out.append(r"\centering")
    if caption:
        out.append(rf"\caption{{{caption}}}")
    if label:
        out.append(rf"\label{{{label}}}")
    out.append(r"\begin{tabular}{@{}lrrr@{}}")
    out.append(r"\toprule")
    out.append(r"Subsystem & JFETs & \% of total & Resistors \\")
    out.append(r"\midrule")
    for r in rows:
        pct = 100.0 * r['njf'] / total_njf if total_njf else 0.0
        out.append(rf"{r['pretty']} & {r['njf']} & {pct:.1f}\% & {r['res']} \\")
    out.append(r"\midrule")
    out.append(rf"\textbf{{Total}} & \textbf{{{total_njf}}} & "
               rf"\textbf{{100.0\%}} & \textbf{{{total_res}}} \\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")
    out.append(r"\end{table}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def print_summary(rows):
    total_njf = sum(r["njf"] for r in rows)
    total_res = sum(r["res"] for r in rows)
    width = max(len(r["pretty"]) for r in rows) + 2
    print(f"{'Subsystem':<{width}}{'Files':>7}{'JFETs':>9}{'Resistors':>12}")
    print("-" * (width + 28))
    for r in rows:
        print(f"{r['pretty']:<{width}}{r['file_count']:>7}{r['njf']:>9}{r['res']:>12}")
    print("-" * (width + 28))
    print(f"{'TOTAL':<{width}}{sum(r['file_count'] for r in rows):>7}{total_njf:>9}{total_res:>12}")


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--cpu", default="4004", help="CPU project under cpus/")
    p.add_argument("--csv", default=None,
                   help="CSV output path (default: paper/data/transistor_count.csv)")
    p.add_argument("--tex", default=None,
                   help="LaTeX output path (default: paper/data/transistor_count.tex)")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    rows = collect(args.cpu)

    csv_path = Path(args.csv) if args.csv else PAPER_DATA_DIR / "transistor_count.csv"
    tex_path = Path(args.tex) if args.tex else PAPER_DATA_DIR / "transistor_count.tex"
    macros_path = tex_path.with_name(tex_path.stem + "_macros.tex")
    write_csv(rows, csv_path)
    write_macros(rows, macros_path)
    write_tex(rows, tex_path,
              caption=("Transistor count of the SiC JFET 4004-compatible processor, "
                       "per subsystem at full capacity (all sixteen scratch-pad registers "
                       "and three stack levels included). Numbers are derived directly from "
                       "the LTspice schematics referenced by \\texttt{cpus/4004/config.py}; "
                       "re-running \\texttt{tools/count\\_transistors.py} regenerates this "
                       "table from the current schematic state."),
              label="tab:transistor-count")

    if not args.quiet:
        print(f"# Transistor count ({args.cpu})")
        print_summary(rows)
        print(f"\nWrote {csv_path}")
        print(f"Wrote {macros_path}")
        print(f"Wrote {tex_path}")


if __name__ == "__main__":
    main()
