#!/usr/bin/env python3
"""Derive expected_state.yaml for a 4004 program by running CPU4004Sim.

The Python reference emulator runs the program from a documented
power-up state and records two register snapshots:

  sync:  state immediately after the first JMS (or after a user-specified
         cycle count). Used by tools/trace_synced.py to align the
         emulator with the LTspice CPU once power-up transients settle.

  final: state when the program halts -- either when the stack underflows
         (top-level BBL), when PC re-enters the program-start NOP, or
         when --max-cycles is reached.

The script is read-only with respect to LTspice artefacts: it only
loads the .asm file in the program directory, runs CPU4004Sim in
memory, and writes expected_state.yaml into the same directory.

Usage:
    python tools/derive_expected_state.py cpus/4004/programs/BitwiseAND
    python tools/derive_expected_state.py <dir> --sync-cycle 6
    python tools/derive_expected_state.py <dir> --max-cycles 20000
    python tools/derive_expected_state.py <dir> --dry-run   # stdout only
"""

import argparse
import importlib.util
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = Path(__file__).resolve().parent

# Power-up state: all DFFs initialise high after power-on in LTspice.
POWERUP_ACC = 0xF
POWERUP_CY = 0
POWERUP_REGS = [0xF] * 16


def load_rom_emulator():
    spec = importlib.util.spec_from_file_location(
        "_rom_emulator", str(TOOLS_DIR / "rom_emulator.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def fmt_yaml_list(items):
    return "[" + ", ".join(str(x) for x in items) + "]"


def render_state_yaml(program_dir: Path, asm_path: Path, sync, final, sync_cycle: int, halt_cycle: int, halt_reason: str):
    name = program_dir.name
    lines = []
    lines.append(f"# Auto-generated by tools/derive_expected_state.py")
    lines.append(f"# Re-run after editing {asm_path.name} to refresh.")
    lines.append(f"")
    lines.append(f"program: {name}")
    lines.append(f"asm: {asm_path.name}")
    lines.append(f"")
    lines.append(f"# Power-up state assumed by the Python emulator (matches LTspice DFFs at t=0).")
    lines.append(f"powerup:")
    lines.append(f"  acc:  {POWERUP_ACC}")
    lines.append(f"  cy:   {POWERUP_CY}")
    lines.append(f"  regs: {fmt_yaml_list(POWERUP_REGS)}")
    lines.append(f"")
    lines.append(f"# Sync point for tools/trace_synced.py.")
    lines.append(f"# Run the emulator forward this many instruction boundaries from power-up,")
    lines.append(f"# then expect the LTspice CPU to be in the state below.")
    lines.append(f"sync:")
    lines.append(f"  after_cycle: {sync_cycle}")
    lines.append(f"  acc:  {sync['acc']}")
    lines.append(f"  cy:   {sync['cy']}")
    lines.append(f"  regs: {fmt_yaml_list(sync['regs'])}")
    lines.append(f"")
    lines.append(f"# Final state when the program halts (or at --max-cycles).")
    lines.append(f"final:")
    lines.append(f"  halted_at_cycle: {halt_cycle}")
    lines.append(f"  reason: {halt_reason}")
    lines.append(f"  acc:  {final['acc']}")
    lines.append(f"  cy:   {final['cy']}")
    lines.append(f"  regs: {fmt_yaml_list(final['regs'])}")
    return "\n".join(lines) + "\n"


def find_asm(program_dir: Path) -> Path:
    cands = list(program_dir.glob("*.asm"))
    if not cands:
        sys.exit(f"ERROR: no .asm file in {program_dir}")
    if len(cands) > 1:
        sys.exit(f"ERROR: multiple .asm files in {program_dir}: {cands}")
    return cands[0]


def snapshot(cpu):
    return {"acc": cpu.acc, "cy": cpu.cy, "regs": list(cpu.regs)}


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("program_dir", help="path to cpus/<cpu>/programs/<name>/")
    p.add_argument("--sync-cycle", type=int, default=None,
                   help="instruction count for sync snapshot "
                        "(default: first cycle after the first JMS completes)")
    p.add_argument("--max-cycles", type=int, default=20000,
                   help="hard ceiling on instructions executed (default 20000)")
    p.add_argument("--dry-run", action="store_true",
                   help="print YAML to stdout instead of writing the file")
    args = p.parse_args()

    program_dir = Path(args.program_dir).resolve()
    if not program_dir.is_dir():
        sys.exit(f"ERROR: {program_dir} is not a directory")

    asm_path = find_asm(program_dir)
    asm_text = asm_path.read_text(encoding="utf-8")

    rom_emulator = load_rom_emulator()
    rom = rom_emulator.assemble(asm_text)
    cpu = rom_emulator.CPU4004Sim(rom)

    # Apply documented power-up state.
    cpu.acc = POWERUP_ACC
    cpu.cy = POWERUP_CY
    cpu.regs = list(POWERUP_REGS)

    sync_snapshot = None
    halt_reason = f"max-cycles ({args.max_cycles}) reached"
    halt_cycle = args.max_cycles

    for cycle in range(1, args.max_cycles + 1):
        pc_before = cpu.pc
        b1 = rom[pc_before] if pc_before < len(rom) else 0x00

        # Detect stack underflow before executing (top-level BBL halts).
        opr = (b1 >> 4) & 0xF
        # Reach end of ROM (PC has fallen off the end with no more bytes)
        if pc_before >= len(rom):
            halt_reason = f"PC={pc_before} past end of ROM ({len(rom)} bytes)"
            halt_cycle = cycle - 1
            break

        # Execute
        try:
            _ = cpu.execute_one()
        except Exception as e:
            halt_reason = f"emulator raised {type(e).__name__}: {e}"
            halt_cycle = cycle - 1
            break

        # Auto sync: snapshot right after the first JMS finishes.
        if sync_snapshot is None:
            if args.sync_cycle is not None and cycle == args.sync_cycle:
                sync_snapshot = snapshot(cpu)
            elif args.sync_cycle is None and opr == 0x5:
                sync_snapshot = snapshot(cpu)
                args.sync_cycle = cycle  # remember the cycle we picked

        # Halt condition: terminating NOP after BBL returns past entry.
        # We use a heuristic: if execute_one decoded a BBL (opr=0xC) and
        # the next ROM byte is a NOP and PC now points at it, we're done.
        if opr == 0xC and cpu.pc < len(rom) and rom[cpu.pc] == 0x00 \
                and cpu.stack_ptr == 0:
            # Run one more cycle (the NOP itself) and stop.
            cpu.execute_one()
            halt_reason = "BBL returned to terminating NOP"
            halt_cycle = cycle + 1
            break

    if sync_snapshot is None:
        # Fallback: use the very first executed-instruction state.
        sync_snapshot = snapshot(cpu)
        if args.sync_cycle is None:
            args.sync_cycle = halt_cycle

    final_snapshot = snapshot(cpu)
    yaml_text = render_state_yaml(
        program_dir, asm_path,
        sync=sync_snapshot, final=final_snapshot,
        sync_cycle=args.sync_cycle,
        halt_cycle=halt_cycle,
        halt_reason=halt_reason,
    )

    if args.dry_run:
        sys.stdout.write(yaml_text)
        return

    out_path = program_dir / "expected_state.yaml"
    out_path.write_text(yaml_text, encoding="utf-8")
    print(f"# Wrote {out_path}")
    print(f"#   sync at cycle {args.sync_cycle}:  ACC={sync_snapshot['acc']:X}"
          f" CY={sync_snapshot['cy']}"
          f" regs=[{','.join(f'{r:X}' for r in sync_snapshot['regs'])}]")
    print(f"#   final at cycle {halt_cycle}:    ACC={final_snapshot['acc']:X}"
          f" CY={final_snapshot['cy']}"
          f" regs=[{','.join(f'{r:X}' for r in final_snapshot['regs'])}]")
    print(f"#   halt reason: {halt_reason}")


if __name__ == "__main__":
    main()
