#!/usr/bin/env python3
"""Generate an LTspice .cir test bench for the f_max corner sweep.

The test article is a chain of N SiC JFET RTL inverters driven by a
square-wave clock. LTspice runs a parametric `.step dec` sweep over
the clock frequency. For each frequency, `.meas` directives extract:

    v_oh : peak output high voltage  (should approach -0.8 V)
    v_ol : minimum output low voltage (should approach -3.6 V)
    t_pd : input-to-output propagation delay at the logic threshold
    swing: V_OH - V_OL (loss-of-swing indicator)

The maximum sustainable clock frequency is the highest .step value at
which `swing` and the noise margins are still positive.

This script does NOT run LTspice. It writes one .cir file. You run it
in LTspice yourself when convenient (GUI: File / Open / Run, or
batch: `LTspice.exe -b analysis/sweeps/freq_testbench.cir`). After the
run, `tools/analyze_ltspice_log.py --sweep freq` parses the .log into
paper/data/freq_sweep.{csv,tex,macros}.

Usage:
    python tools/gen_freq_testbench.py                 # default N=4
    python tools/gen_freq_testbench.py --chain 6
    python tools/gen_freq_testbench.py --fmin 10k --fmax 2Meg
"""

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "tools"))

from _spice_emit import (
    load_cpu_config, model_card, inverter_subckt, supplies_block,
    gate_resistors, fmt_r,
)

OUT_DIR = PROJECT_ROOT / "analysis" / "sweeps"


def emit_cir(cfg, *, chain: int, fmin: str, fmax: str, n_per_dec: int,
             gate_name: str, pulse_high: float, pulse_low: float) -> str:
    rvals = gate_resistors(cfg, gate_name)
    r1, r2, r3 = fmt_r(rvals["r1"]), fmt_r(rvals["r2"]), fmt_r(rvals["r3"])

    # Build the chain wiring: in -> n1 -> n2 -> ... -> nN ("nN" is "out").
    chain_lines = []
    prev = "in"
    for i in range(1, chain + 1):
        nxt = "out" if i == chain else f"n{i}"
        chain_lines.append(f"X{i} {prev} {nxt} VPOS VNEG INV2J")
        prev = nxt

    lines = [
        f"* SiC JFET RTL inverter chain (N={chain}): frequency sweep test bench",
        f"* Generated by tools/gen_freq_testbench.py from cpus/4004/config.py.",
        f"* Do not edit by hand -- re-run the generator after tuning the CPU.",
        f"",
        f"* --- device model ---",
        model_card(cfg, model_name="DR"),
        f"",
        f"* --- supplies (fixed at config.py nominal) ---",
        supplies_block(cfg),
        f"",
        f"* --- 2-JFET inverter subcircuit with hand-tuned R values ---",
        inverter_subckt(cfg, r1=r1, r2=r2, r3=r3, model_name="DR"),
        f"",
        f"* --- swept clock frequency ---",
        f".param freq=100k",
        f"V_IN in 0 PULSE({pulse_low:g} {pulse_high:g}"
        f" 100n 100n 100n {{0.5/freq}} {{1/freq}})",
        f"",
        f"* --- N-inverter chain under test ---",
    ]
    lines.extend(chain_lines)
    lines += [
        f"",
        f"* --- sweep ---",
        f".step dec param freq {fmin} {fmax} {n_per_dec}",
        f"",
        f"* --- transient ---",
        f"* Run 20 clock periods, log the final settled period only.",
        f".tran 0 {{20/freq}} {{18/freq}} {{0.01/freq}}",
        f"",
        f"* --- measurements (one row per step in the .log) ---",
        f".meas tran v_oh MAX V(out) FROM={{18.5/freq}} TO={{20/freq}}",
        f".meas tran v_ol MIN V(out) FROM={{18.5/freq}} TO={{20/freq}}",
        f".meas tran swing PARAM v_oh-v_ol",
        f"* Propagation delay across the {chain}-gate chain, mid-rail threshold.",
        f"* (For an even chain length, in and out are in phase; threshold = -2.2 V.)",
        f".meas tran t_pd_rise"
        f" TRIG V(in)  VAL=-2.2 RISE=1"
        f" TARG V(out) VAL=-2.2 RISE=1",
        f".meas tran t_pd_fall"
        f" TRIG V(in)  VAL=-2.2 FALL=1"
        f" TARG V(out) VAL=-2.2 FALL=1",
        f"",
        f".end",
    ]
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--cpu", default="4004")
    p.add_argument("--gate", default="INV", choices=("INV", "NAND2", "NOR2"))
    p.add_argument("--chain", type=int, default=4,
                   help="number of inverters in the chain (default 4)")
    p.add_argument("--fmin", default="10k",
                   help="lowest frequency for .step (default 10k)")
    p.add_argument("--fmax", default="2Meg",
                   help="highest frequency for .step (default 2Meg)")
    p.add_argument("--per-decade", type=int, default=10,
                   help="logarithmic steps per decade (default 10)")
    p.add_argument("--pulse-high", type=float, default=-0.8,
                   help="logic-high voltage of the clock (default -0.8)")
    p.add_argument("--pulse-low", type=float, default=-3.6,
                   help="logic-low voltage of the clock (default -3.6)")
    p.add_argument("--out", default=None,
                   help="output path (default analysis/sweeps/freq_testbench.cir)")
    args = p.parse_args()

    if args.chain % 2 != 0:
        sys.exit(f"ERROR: --chain must be even for in/out phase matching;"
                 f" got {args.chain}")

    cfg = load_cpu_config(args.cpu)
    text = emit_cir(
        cfg,
        chain=args.chain,
        fmin=args.fmin, fmax=args.fmax, n_per_dec=args.per_decade,
        gate_name=args.gate,
        pulse_high=args.pulse_high, pulse_low=args.pulse_low,
    )
    out_path = Path(args.out) if args.out else OUT_DIR / "freq_testbench.cir"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"# Wrote {out_path}")
    print(f"#   chain length: {args.chain} inverters")
    print(f"#   frequency sweep: {args.fmin} .. {args.fmax}, "
          f"{args.per_decade} pts/decade")
    print(f"#   R values: R1={fmt_r(cfg.GATES[args.gate]['r1'])} "
          f"R2={fmt_r(cfg.GATES[args.gate]['r2'])} "
          f"R3={fmt_r(cfg.GATES[args.gate]['r3'])}")
    print(f"#   supplies: V_POS={cfg.V_POS} V, V_NEG={cfg.V_NEG} V")
    print(f"#")
    print(f"# Run it in LTspice:")
    print(f"#   GUI:    open {out_path.relative_to(PROJECT_ROOT)} and hit Run")
    print(f"#   batch:  LTspice.exe -b {out_path.relative_to(PROJECT_ROOT)}")
    print(f"# Then:    python tools/analyze_ltspice_log.py --sweep freq")


if __name__ == "__main__":
    main()
