#!/usr/bin/env python3
"""Generate LTspice .cir test benches for the R/V sensitivity sweep.

Five test benches are emitted, one per swept parameter, so that each
result table cleanly attributes margin loss to a single axis:

    sensitivity_r1.cir     R1 swept over ~0.8 .. 1.2 x nominal
    sensitivity_r2.cir     R2 swept similarly
    sensitivity_r3.cir     R3 swept similarly
    sensitivity_vpos.cir   V_POS swept by +/- 2 V around nominal
    sensitivity_vneg.cir   V_NEG swept similarly

The test article in every case is a single 2-JFET inverter (from the
shared subcircuit in tools/_spice_emit.py), driven by a slow square
wave at 10 kHz so the transient settles fully at each step. `.meas`
extracts V_OH, V_OL, and the rise/fall propagation delays per step.

LTspice runs these as a normal `.step param ... list` sweep -- no
external scripting required. After the runs, point
`tools/analyze_ltspice_log.py --sweep sensitivity` at the
analysis/sweeps/ directory and it will read every sensitivity_*.log
and emit paper/data/sensitivity.{csv,tex,macros}.

Usage:
    python tools/gen_sensitivity_testbench.py                 # all five
    python tools/gen_sensitivity_testbench.py --only r1       # one
    python tools/gen_sensitivity_testbench.py --scales 0.9,1.0,1.1
"""

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "tools"))

from _spice_emit import (
    load_cpu_config, model_card, inverter_subckt, supplies_block_param,
    gate_resistors, fmt_r,
)

OUT_DIR = PROJECT_ROOT / "analysis" / "sweeps"

DEFAULT_CLOCK_FREQ_HZ = 10e3  # slow enough that 100 kHz CPU has full settle


def _spice_list(values):
    return " ".join(f"{v:g}" for v in values)


def emit_cir(cfg, *, swept: str, sweep_values, gate_name: str,
             clock_freq_hz: float) -> str:
    """Emit a single .cir with one parameter swept.

    swept: one of "r1", "r2", "r3", "vpos", "vneg"
    sweep_values: list of absolute values (ohms for R, volts for V)
    """
    rvals = gate_resistors(cfg, gate_name)
    r_param = {"r1": "{r1}", "r2": "{r2}", "r3": "{r3}"}
    for k in r_param:
        if swept != k:
            r_param[k] = fmt_r(rvals[k])

    v_pos = "{vpos}" if swept == "vpos" else f"{cfg.V_POS:.4g}"
    v_neg = "{vneg}" if swept == "vneg" else f"{cfg.V_NEG:.4g}"

    # Declare .param defaults so non-swept ones still resolve.
    param_lines = []
    if swept == "r1":
        param_lines.append(f".param r1={rvals['r1']:g}")
    if swept == "r2":
        param_lines.append(f".param r2={rvals['r2']:g}")
    if swept == "r3":
        param_lines.append(f".param r3={rvals['r3']:g}")
    if swept == "vpos":
        param_lines.append(f".param vpos={cfg.V_POS:.4g}")
    if swept == "vneg":
        param_lines.append(f".param vneg={cfg.V_NEG:.4g}")

    period_s = 1.0 / clock_freq_hz
    half_period_s = period_s / 2.0
    end_t = 2 * period_s  # two full periods so settle measurement is clean

    lines = [
        f"* SiC JFET inverter: single-axis sensitivity sweep ({swept})",
        f"* Generated by tools/gen_sensitivity_testbench.py from cpus/4004/config.py.",
        f"* Do not edit by hand -- re-run the generator after tuning the CPU.",
        f"",
        model_card(cfg, model_name="DR"),
        f"",
        f"* Supplies (use .param so V can be swept on this axis if applicable)",
        f".param vpos={cfg.V_POS:.4g}",
        f".param vneg={cfg.V_NEG:.4g}",
        supplies_block_param(),
        f"",
        f"* Hand-tuned R values (the swept one is overridden by .step below)",
    ]
    lines.extend(param_lines)
    lines += [
        f"",
        inverter_subckt(cfg,
                        r1=r_param['r1'], r2=r_param['r2'], r3=r_param['r3'],
                        model_name="DR"),
        f"",
        f"* Test instance",
        f"X1 in out VPOS VNEG INV2J",
        f"",
        f"* Slow clock -- {clock_freq_hz:g} Hz, square wave between rails",
        f"V_IN in 0 PULSE(-3.6 -0.8 100n 100n 100n {half_period_s:g} {period_s:g})",
        f"",
        f"* Sweep",
        f".step param {swept} list {_spice_list(sweep_values)}",
        f"",
        f"* Two full periods; settle measurements come from the second.",
        f".tran 0 {end_t:g} {period_s:g} {period_s/1000:g}",
        f"",
        f"* Measurements (one row per step in the .log).",
        f".meas tran v_oh MAX V(out) FROM={period_s*1.5:g} TO={period_s*2:g}",
        f".meas tran v_ol MIN V(out) FROM={period_s:g} TO={period_s*1.5:g}",
        f".meas tran swing PARAM v_oh-v_ol",
        f".meas tran t_pd_rise"
        f" TRIG V(in)  VAL=-2.2 RISE=1"
        f" TARG V(out) VAL=-2.2 FALL=1",
        f".meas tran t_pd_fall"
        f" TRIG V(in)  VAL=-2.2 FALL=1"
        f" TARG V(out) VAL=-2.2 RISE=1",
        f"",
        f".end",
    ]
    return "\n".join(lines) + "\n"


def build_sweep_values(cfg, swept: str, scales) -> list:
    if swept in ("r1", "r2", "r3"):
        nominal = cfg.GATES["INV"][swept]
        return [nominal * s for s in scales]
    if swept == "vpos":
        return [cfg.V_POS - 2, cfg.V_POS - 1, cfg.V_POS,
                cfg.V_POS + 1, cfg.V_POS + 2]
    if swept == "vneg":
        return [cfg.V_NEG - 2, cfg.V_NEG - 1, cfg.V_NEG,
                cfg.V_NEG + 1, cfg.V_NEG + 2]
    raise ValueError(f"unknown swept axis {swept}")


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--cpu", default="4004")
    p.add_argument("--gate", default="INV", choices=("INV", "NAND2", "NOR2"))
    p.add_argument("--scales", default="0.8,0.9,1.0,1.1,1.2",
                   help="comma-separated R scale factors (default 0.8..1.2)")
    p.add_argument("--clock-freq", type=float, default=DEFAULT_CLOCK_FREQ_HZ)
    p.add_argument("--only", default=None,
                   choices=("r1", "r2", "r3", "vpos", "vneg"),
                   help="emit only one of the five .cir files")
    args = p.parse_args()

    scales = [float(s) for s in args.scales.split(",") if s.strip()]
    cfg = load_cpu_config(args.cpu)
    axes = [args.only] if args.only else ["r1", "r2", "r3", "vpos", "vneg"]

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for axis in axes:
        values = build_sweep_values(cfg, axis, scales)
        text = emit_cir(cfg, swept=axis, sweep_values=values,
                        gate_name=args.gate, clock_freq_hz=args.clock_freq)
        path = OUT_DIR / f"sensitivity_{axis}.cir"
        path.write_text(text, encoding="utf-8")
        if axis.startswith("r"):
            disp = ", ".join(f"{v/1e3:g}k" for v in values)
        else:
            disp = ", ".join(f"{v:g}V" for v in values)
        print(f"# Wrote {path}  ({axis}: {disp})")

    print()
    print("# Run each in LTspice (GUI: open + Run, or batch: LTspice -b file.cir),")
    print("# then: python tools/analyze_ltspice_log.py --sweep sensitivity")


if __name__ == "__main__":
    main()
