#!/usr/bin/env python3
"""Regenerate every data artefact the paper depends on.

Run this from the repository root (or from inside `paper/`) any time the
CPU schematics, test programs, or analysis scripts change. All outputs
under `paper/data/` are overwritten; everything else is left alone.

Each generator is independent. If a generator's `requires` file does not
exist yet (typical case: LTspice .raw not produced yet for a new
program), the step is skipped with a one-line note rather than failing
the whole build.

Add new generators to GENERATORS below as Weeks 3-5 land.

Usage:
    python paper/regen_data.py              # run everything available
    python paper/regen_data.py --only count # run one step
    python paper/regen_data.py --list       # list available steps
"""

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS = REPO_ROOT / "tools"
PAPER_DATA = REPO_ROOT / "paper" / "data"
PROGRAMS = REPO_ROOT / "cpus" / "4004" / "programs"


def run(label, cmd):
    print(f"\n=== {label} ===")
    print("$ " + " ".join(str(c) for c in cmd))
    result = subprocess.run(cmd, cwd=REPO_ROOT)
    if result.returncode != 0:
        print(f"!! {label} failed (exit {result.returncode}); continuing.",
              file=sys.stderr)
        return False
    return True


def skip(label, reason):
    print(f"\n=== {label} ===")
    print(f"-- SKIPPED: {reason}")


# Each entry is a dict so future fields can be added without breaking
# existing callers. Required: key, label, cmd. Optional: requires (a
# Path; if it does not exist when regen runs, the step is skipped).
GENERATORS = [
    {
        "key":   "count",
        "label": "Transistor count per subsystem",
        "cmd":   [sys.executable, str(TOOLS / "count_transistors.py"),
                  "--cpu", "4004", "--quiet"],
    },
    # Each trace step is gated by a SIM_COMPLETE sentinel inside the
    # program directory. Touching that file is the user's explicit
    # signal that the LTspice transient is done and the .raw is safe
    # to read. This prevents `paper/build.py` from racing an in-flight
    # transient sim.
    {
        "key":   "trace_fp",
        "label": "ISA-rule verification of LTspice trace (FloatingPoint)",
        "cmd":   [sys.executable, str(TOOLS / "verify_micro5.py"),
                  "--program", "FloatingPoint",
                  "--start-time", "4", "--quiet"],
        "requires": PROGRAMS / "FloatingPoint" / "SIM_COMPLETE",
    },
    {
        "key":   "trace_and",
        "label": "ISA-rule verification of LTspice trace (BitwiseAND)",
        "cmd":   [sys.executable, str(TOOLS / "verify_micro5.py"),
                  "--program", "BitwiseAND",
                  "--start-time", "0.2", "--quiet"],
        "requires": PROGRAMS / "BitwiseAND" / "SIM_COMPLETE",
    },
    # Week 4 LTspice-driven corner analysis. These ANALYZE the .log
    # files produced by LTspice batch runs over the test-bench .cir
    # files generated by tools/gen_*_testbench.py. The .cir files live
    # in analysis/sweeps/; run them yourself in LTspice when the
    # FloatingPoint sim is done. Each step is gated on its .log
    # existing, so the build skips them until you've actually run the
    # sweep.
    {
        "key":   "freq_sweep",
        "label": "Frequency limit from LTspice gate-chain sweep",
        "cmd":   [sys.executable, str(TOOLS / "analyze_ltspice_log.py"),
                  "--sweep", "freq", "--quiet"],
        "requires": REPO_ROOT / "analysis" / "sweeps" / "freq_testbench.log",
    },
    {
        "key":   "sensitivity",
        "label": "R/V sensitivity from LTspice corner sweeps",
        "cmd":   [sys.executable, str(TOOLS / "analyze_ltspice_log.py"),
                  "--sweep", "sensitivity", "--quiet"],
        "requires_glob": (REPO_ROOT / "analysis" / "sweeps",
                          "sensitivity_*.log"),
    },
]


def precheck(gen):
    """Return (ok, reason). ok=False means skip with reason."""
    if "requires" in gen and not gen["requires"].exists():
        return False, f"missing prerequisite {gen['requires'].relative_to(REPO_ROOT)}"
    if "requires_glob" in gen:
        directory, pattern = gen["requires_glob"]
        if not directory.exists() or not list(directory.glob(pattern)):
            rel = directory.relative_to(REPO_ROOT) if directory.exists() else directory
            return False, f"no {pattern} in {rel}"
    return True, None


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--only", default=None,
                   help="run only this generator key (see --list)")
    p.add_argument("--list", action="store_true",
                   help="list generator keys and exit")
    args = p.parse_args()

    if args.list:
        for gen in GENERATORS:
            print(f"  {gen['key']:<14} {gen['label']}")
        return

    PAPER_DATA.mkdir(parents=True, exist_ok=True)

    failed = []
    skipped = []
    for gen in GENERATORS:
        if args.only and args.only != gen["key"]:
            continue
        ok, reason = precheck(gen)
        if not ok:
            skip(gen["label"], reason)
            skipped.append(gen["key"])
            continue
        if not run(gen["label"], gen["cmd"]):
            failed.append(gen["key"])

    print()
    if skipped:
        print(f"-- skipped {len(skipped)}: {', '.join(skipped)}")
    if failed:
        print(f"!! {len(failed)} step(s) failed: {', '.join(failed)}")
        sys.exit(1)
    print(f"OK -- artefacts written to {PAPER_DATA}")


if __name__ == "__main__":
    main()
